<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_template.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_templates']['title'] = array('Bezeichnung','Bezeichnung der Vorlage');
$GLOBALS['TL_LANG']['tl_iao_templates']['text'] = array('Vorlagen-Text','');
$GLOBALS['TL_LANG']['tl_iao_templates']['position'] = array('Position','');
$GLOBALS['TL_LANG']['tl_iao_templates']['new'] = array('Neue Vorlage','Eine neue Vorlage anlegen');
$GLOBALS['TL_LANG']['tl_iao_templates']['edit'] = array('Vorlage bearbeiten','Vorlage ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_iao_templates']['copy'] = array('Vorlage duplizieren','Vorlage ID %s duplizieren');
$GLOBALS['TL_LANG']['tl_iao_templates']['delete'] = array('Vorlage löschen','Vorlage ID %s löschen');

$GLOBALS['TL_LANG']['tl_iao_templates']['template_options'] = array(
    'invoice_before_text'=>'Rechnung Text vor Positionen',
    'invoice_after_text'=>'Rechnung Text nach Positionen',
    'offer_before_text'=>'Angebot Text vor Positionen',
    'offer_after_text'=>'Angebot Text nach Positionen',
    'credit_before_text'=>'Gutschrift Text vor Positionen',
    'credit_after_text'=>'Gutschrift Text nach Positionen',
    );